[variables]
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs", "python311"]

[phases.install]
cmds = [
    "cd frontend && npm ci --production=false",
    "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "cd backend && python -m uvicorn server:app --host 0.0.0.0 --port $PORT"