[variables]
NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "cd frontend && npm ci --production=false",
    "cd backend && pip install -r requirements_simple.txt"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "./start.sh"